name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
      - uses: actions/checkout@v1
        env: 
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
        git clone git@github.com:jasonjx-w/jasonjx-w.github.io.git template
      #  docker run \
      #  -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
      #  jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
      # with:
      #   repo-token: ${{ secrets.GITHUB_TOKEN }}
