name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      uses: actions/checkout@v2
    steps:
    - name: nothing
      uses: jasonjx-w/jasonjx-w.github.io@master
