name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      uses: jasonjx-w/jasonjx-w.github.io@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
