name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Build the site in the jekyll/builder container
    - uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone git@github.com:jasonjx-w/jasonjx-w.github.io.git template
        ls
        # docker run \
        # -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        # jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
